version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: surveys_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./server/init/survey_database.sql:/docker-entrypoint-initdb.d/survey_database.sql

  nodejs-app:
    build: ./server
    container_name: nodejs_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: surveys_db

  client:
    build: ./client
    container_name: client_app
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-app

